---
- name: Install the logwatch packages 
  ansible.builtin.package: 
    name: logwatch 
    state: present
  tags: 
    - logwatch
    - logwatch-package

- name: Configure logwatch
  ansible.builtin.template: 
    src: logwatch.conf.j2 
    dest: /etc/logwatch/conf/logwatch.conf
  tags: 
    - logwatch
    - logwatch-config
